title: Cartão do Cachaceiro
description: Aplicativo oficial para gerar o cartão do cachaceiro. Informações, políticas e atualizações.
theme: jekyll-theme-minimal

# Links da navegação
nav:
  - name: Home
    link: /
  - name: Privacy Policy
    link: /privacy-policy.html
  - name: About the Project
    link: /about.html
